---
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 36000

- name: Install base packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - build-essential
    - curl
    - gdb
    - git
    - silversearcher-ag
    - sudo
    - vim

- name: Install vim-plug and Vim plugins
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +'PlugInstall --sync' +qa
  args:
    executable: /bin/bash
    warn: False

